@startuml
node "User Browser" as UserBrowser

node "Web Application Server" as WebApp {
    [Nextjs]
}

node "Administration Server" as AdminJS {
    [AdminJS Panel]
    
}

cloud "External Services" as ExternalServices {
    [MinIO]
    [PlantUML Server]
    [AI Model]
}

node "Database Server" as Database {
    [PostgreSQL]
}

UserBrowser --> WebApp :  Perform Actions / Use Features
UserBrowser --> AdminJS : Manage Data
WebApp ---> [PostgreSQL] : Prisma Queries
AdminJS ---> [PostgreSQL] : Prisma Queries
WebApp ---> [MinIO] : Upload/Download Files
WebApp ---> [PlantUML Server] : Generate UML Diagrams
WebApp ---> [AI Model] : Send Requests for AI Processing
@enduml
