@startuml

left to right direction

actor "User" as User


rectangle "Web Applicate" {
    usecase "Explore Landing Page" as ExploreLandingPage
    usecase "Authenticate" as user_auth

    usecase "Interact in the community" as InteractWithCommunity
    usecase "Manage projects" as ManageProjects
    usecase "Manage diagrams" as ManageDiagrams
    usecase "Manage workspace" as ManageWorkspace
    usecase "Manage profile" as EditProfile

    

}



User -- ExploreLandingPage
User -- InteractWithCommunity
User -- ManageProjects
User -- ManageDiagrams
User -- EditProfile
User -- ManageWorkspace



InteractWithCommunity ..> user_auth : <<include>>
ManageProjects ..> user_auth : <<include>>
ManageDiagrams ..> user_auth : <<include>>
ManageWorkspace ..> user_auth : <<include>>
EditProfile ..> user_auth : <<include>>







@enduml