@startuml
title View Project - Sequence Diagram

actor User
boundary Frontend
control Backend
boundary MinIO
database Database

ref over User, Database: Authenticate

activate Frontend

User -> Frontend: Click on project
Frontend -> Backend: Request project details
activate Backend

Backend -> Database: Get project info & diagram list
activate Database
Database --> Backend: Return project data 
deactivate Database


Backend --> Frontend: Send project data 
Frontend --> Backend: Request diagram images by links


Backend -> MinIO: Request diagram images 
activate MinIO
MinIO --> Backend: Return diagram images
deactivate MinIO

Backend --> Frontend: Return diagram images

deactivate Backend

Frontend -> Frontend: Display project information
Frontend -> Frontend: Render diagram thumbnails
Frontend --> User: Show project workspace with diagrams
deactivate Frontend

@enduml