@startuml
left to right direction

actor "User" as User
node "AI Model" as AIModel
node "PlantUML Server" as PlantUMLServer
node "MinIo" as MinIo

rectangle "Web Application" {
    usecase "Manage Workspace" as ManageWorkspace#Yellow
    usecase "chat with AI" as ChatWithAI
    usecase "edit diagram" as EditDiagram
    usecase "save changes" as SaveChanges

    usecase "Download Diagram Image" as DownloadDiagramImage
    usecase "download as svg format" as DownloadSVGFormat
    usecase "download as png format" as DownloadPNGFormat
}

User -- ManageWorkspace

ManageWorkspace <|-- ChatWithAI
ManageWorkspace <|-- SaveChanges
ManageWorkspace <|-- EditDiagram
ManageWorkspace <|-- DownloadDiagramImage
ChatWithAI <.. EditDiagram : <<extend>>
DownloadDiagramImage <.. DownloadSVGFormat : <<extend>>
DownloadDiagramImage <.. DownloadPNGFormat : <<extend>>
DownloadSVGFormat -- PlantUMLServer
DownloadPNGFormat -- PlantUMLServer
EditDiagram -- PlantUMLServer
SaveChanges -- MinIo 

ChatWithAI -- AIModel


@enduml