@startuml
left to right direction

actor "User" as User

rectangle "Web Application" {
    usecase "Manage diagrams" as ManageDiagrams#Yellow
    usecase "Create Diagram" as CreateDiagram
    usecase "View Diagram" as ViewDiagram
    usecase "Delete Diagram" as DeleteDiagram
}

User -- ManageDiagrams

ManageDiagrams <|-- CreateDiagram
ManageDiagrams <|-- ViewDiagram
ManageDiagrams <|-- DeleteDiagram
@enduml