@startuml
left to right direction

actor "User" as User
node "MinIo" as MinIo
node "AI Model" as AIModel
node "PlantUML Server" as PlantUMLServer


rectangle "Web Application" {
    usecase "Manage Workspace" as ManageWorkspace#Yellow
    usecase "chat with AI" as ChatWithAI
    usecase "clear chat" as ClearChat
    usecase "edit diagram" as EditDiagram
    usecase "save changes" as SaveChanges

    usecase "Download Diagram Image" as DownloadDiagramImage

}

User -- ManageWorkspace
ChatWithAI --- AIModel
 

ManageWorkspace <|-- ChatWithAI
EditDiagram <.. SaveChanges : <<extend>>
ManageWorkspace <|-- EditDiagram
ManageWorkspace <|-- DownloadDiagramImage
ChatWithAI <.. ClearChat : <<extend>>


SaveChanges -- MinIo 


DownloadDiagramImage --- PlantUMLServer

EditDiagram --- PlantUMLServer


@enduml