@startuml
node "User Browser" as UserBrowser

node "Web Application Server" as WebApp {
    [WebApp Container]
}

node "Administration Server" as AdminJS {
    [AdminJS Panel]
    
}

cloud "External Services" as ExternalServices {
    [MinIO API]
    [PlantUML Server API]
    [AI Model API]
}

node "Database Server" as Database {
    [PostgreSQL]
}

UserBrowser --> WebApp :  Perform Actions / Use Features
UserBrowser --> AdminJS : Manage Data
WebApp ---> [PostgreSQL] : Prisma Queries
AdminJS ---> [PostgreSQL] : Prisma Queries
WebApp ---> [MinIO API] : Upload/Download Files
WebApp ---> [PlantUML Server API] : Generate UML Diagrams
WebApp ---> [AI Model API] : Send Requests for AI Processing
@enduml
