@startuml

left to right direction

actor "User" as User
node "PlantUML Server" as PlantUMLServer

rectangle "Web Application" {
    usecase "Manage projects" as ManageProjects #Yellow
    usecase "Create new project" as CreateNewProject
    usecase "View project" as ViewProject
    usecase "Update project details" as UpdateProjectDetails
    usecase "Delete project" as DeleteProject
    usecase "Download project diagrams compressed" as DownloadProjectDiagrams

}

User -- ManageProjects

ManageProjects <|-- CreateNewProject
ManageProjects <|-- ViewProject
ManageProjects <|-- UpdateProjectDetails
ManageProjects <|-- DeleteProject
ManageProjects <|-- DownloadProjectDiagrams

DownloadProjectDiagrams -- PlantUMLServer
@enduml
